# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmdpeek" do
  version "0.0.17"

  on_macos do
    on_arm do
      sha256 "5b64361e489be50b80a3d73604f1742a5b7c0771367518a7bc05452ae07596bd"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6bc2244ecfa9154a0499ad5fa233caf59090da0f7cb1a55f08a72b7a480feb5"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "208e9252dbd763f57f787853dc5e5c75b5d8a681f7e83a30bfdaed1d5193ef0b"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "22bcd8676523d8ea8a95f46b8c30454e836aad35ad9bbbc2e5e1610e8c7e0252"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "cmdpeek"
  desc "Searchable interactive command palette for reusable terminal workflows"
  homepage "https://github.com/pierinho13/cmdpeek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmdpeek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/cmdpeek"
        ]
    end
  end

  # No zap stanza required
end
