# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmdpeek" do
  version "0.0.16"

  on_macos do
    on_arm do
      sha256 "0b0adb20fd276763d1b8edb1c0932abab128b417939cf19b9977491fc7f869f7"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d613c0380a6ca9bd25b51ccf6bc27a11c858da346ea71bb1ea3802674ddf53c"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "65ae26f8f643c060e06ec1952146b0735899a67157dbfb6090eacf21e9514a8e"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e12a579a10c90f7cc9e830ba38c02fc3b1043f96060cefbf88eec63f6f37d11b"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "cmdpeek"
  desc "Searchable interactive command palette for reusable terminal workflows"
  homepage "https://github.com/pierinho13/cmdpeek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmdpeek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/cmdpeek"
        ]
    end
  end

  # No zap stanza required
end
