# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-peek" do
  version "0.1.22"

  on_macos do
    on_arm do
      sha256 "c96b8bed65dbeb71efdb94ac93cc323d7602436ea3a54f7587de09259a4f6a52"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2dc29abd83bccf3b80cd2e99966a009233af322fb4d5a1c0dda1973df3128a1"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "33625ef25cca2d74975c8a4d19f305d1cc9a6c2a820f5f0e1b9ec3c1ddd66e8f"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc93152dcc72188c9f40b171cf6a4052040e673908a921f3c32f89237bb0f8d4"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "kubectl-peek"
  desc "Simple interactive kubectl plugin for browsing Secrets and discovering where they are used"
  homepage "https://github.com/pierinho13/kubectl-peek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-peek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/kubectl-peek"
        ]
    end
  end

  # No zap stanza required
end
