# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-peek" do
  version "0.1.21"

  on_macos do
    on_arm do
      sha256 "29d734d0f285a2f4e6c138a75aa6b15d5bd861c9e1233f177f2459ad6b706f4d"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ed8291239649230869b2dcf17a50c7e59aa54ec79f688b29fd86d8cd60554d7"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0b1d69a40acfdbd1cb154783f60d44b5829b1fce07561952e5e79370a6917d5"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b3d46186db8f29ca53be09eadf6ee63e0a170be7e7d85cf38f44e86701d1abd"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "kubectl-peek"
  desc "Simple interactive kubectl plugin for browsing Secrets and discovering where they are used"
  homepage "https://github.com/pierinho13/kubectl-peek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-peek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/kubectl-peek"
        ]
    end
  end

  # No zap stanza required
end
