# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-peek" do
  version "0.1.20"

  on_macos do
    on_arm do
      sha256 "fa1f903b7d5263be872898b7271dba97a11774fffde3b49dd8c79c176b8e471d"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1923756019c834665994a115b00276102e288e085585215cda3da562846a43f"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7474af143ae625555cfaf8fa8ddcc435ab5eb53dc3a5012e9826e4264f920e0f"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5696e1e326ea4401aabd15c748aab5d253aea08c1da9ac864dc1899a2eb5ceff"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "kubectl-peek"
  desc "Simple interactive kubectl plugin for browsing Secrets and discovering where they are used"
  homepage "https://github.com/pierinho13/kubectl-peek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-peek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/kubectl-peek"
        ]
    end
  end

  # No zap stanza required
end
